Rio1.UI/Controllers/AspNetRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Rio1.UI.Models;

namespace Rio1.UI.Controllers
{
    public class AspNetRolesController : Controller
    {
      [Authorize(Roles ="Admin")]
        // GET: AspNetRoles
        public ActionResult Index()
        {
            Rio1.Business.GestorDeAspNetRoles gestorDeAspNetRoles = new Business.GestorDeAspNetRoles();
            var Listar = gestorDeAspNetRoles.ListarAspNetRoles();
           
            if (this.Request.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    return View(Listar);
                }
                else
                {
                    return RedirectToAction("VistaAdvertencia");
                }
            }
             else
             {
                    return RedirectToAction("Index");
             }
           
            

        }

        // GET: AspNetRoles/Detalles/5
        public ActionResult Detalles(string id)
        {
            Rio1.Model.AspNetRole aspNetRole;
            Rio1.Business.GestorDeAspNetRoles gestorDeAspNetRoles = new Business.GestorDeAspNetRoles();
            aspNetRole = gestorDeAspNetRoles.ObtenerAspNetRolesPorId(id);
            if (this.Request.IsAuthenticated)
            {
                return View(aspNetRole);
            }
            else {
                return RedirectToAction("Index");
            }
        }

      
        // GET: AspNetRoles/Eliminar/5
        public ActionResult Eliminar(int id)
        {
            Rio1.Business.GestorDeAspNetRoles gestordeAspNetRoles = new Business.GestorDeAspNetRoles();
            Rio1.Model.AspNetRole aspNetRole;


            return View();
        }

        // POST: AspNetRoles/Eliminar/5
        [HttpPost]
        public ActionResult Eliminar(string id, Model.AspNetRole aspNetRole)
        {
            try
            {
                Rio1.Business.GestorDeAspNetRoles gestor = new Business.GestorDeAspNetRoles();

                aspNetRole = gestor.ObtenerAspNetRolesPorId(id);
                gestor.Eliminar(aspNetRole);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }
    }
}

Rio1.UI/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rio1.UI.Controllers
{
    public class AspNetUsersController : Controller
    {
     [Authorize (Roles ="Admin")]
        // GET: AspNetUsers
        public ActionResult Index()
        {
            Rio1.Business.GestorDeAspNetUsers gestorDeAspNetUsers = new Business.GestorDeAspNetUsers();
            var Listar = gestorDeAspNetUsers.ListarAspNetUser();
            if (this.Request.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                { 
                     return View(Listar);
                }
                else {
                    return View("VistaAdvertencia");
                }
                
            }
                return View("VistaAdvertencia");
            
        }
        public ActionResult VistaGeneral()
        {
            if (this.Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return View("VistaAdvertencia");
            }
        }
        // GET: AspNetUsers/Details/5
        public ActionResult Detallar(string  id)
        {
            Rio1.Model.AspNetUsers aspNetUsers;
            Rio1.Business.GestorDeAspNetUsers gestorDeAspNetUsers = new Business.GestorDeAspNetUsers();
            aspNetUsers = gestorDeAspNetUsers.ObtenerAspNetUsersPorId(id);
            if (this.Request.IsAuthenticated)
            { 
             return View(aspNetUsers);
            }
           
                return View("VistaAdvertencia");
            
        }

       
        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(int id)
        {
            if(this.Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return View("VistaAdvertencia");
            }
        }

        // POST: AspNetUsers/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AspNetUsers/Eliminar/5
        public ActionResult Eliminar(string id)
        {

            Rio1.Business.GestorDeAspNetUsers gestorDeAspNetUsers = new Business.GestorDeAspNetUsers();
            Rio1.Model.AspNetUsers aspNetUsers;
            if (this.Request.IsAuthenticated)
            { 
                return View();
            }
            else
            {
                return View("VistaAdvertencia");
            }
        }

        // POST: AspNetUsers/Eliminar/5
        [HttpPost]
        public ActionResult Eliminar(Rio1.Model.AspNetUsers aspNetUsers, string id)
        {
            try
            {

                Rio1.Business.GestorDeAspNetUsers gestorDeAspNetUsers = new Business.GestorDeAspNetUsers();
                aspNetUsers = gestorDeAspNetUsers.ObtenerAspNetUsersPorId(id);

                gestorDeAspNetUsers.Eliminar(aspNetUsers);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Rio1.UI/Views/AspNetUsers/Detallar.cshtml
@model Rio1.Model.AspNetUsers

@{
    ViewBag.Title = "DetallarUsuario";
}
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="~/Content/Estilos.css">
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale-1.0, maximun-scale=3.0, minimun-scale=1.0">

</head>
<br />
<br />
<center><div class=" contenedor"><center><h2>Datos del usuario</h2></center></div></center>
<br />
<br />

<center>
    <div class=" TablaFormato">
        <br />
        <h4>Información del usuario</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>


        </dl>
    </div>
</center>

<p><a class="btn btn-success" @Html.ActionLink("Regresar usuarios", "Index")</a></p>

Rio1.UI/Views/AspNetUsers/Eliminar.cshtml
@model Rio1.Model.AspNetUsers

@{
    ViewBag.Title = "Eliminar";
}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/Content/Estilos.css">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale-1.0, maximun-scale=3.0, minimun-scale=1.0">

</head>
<br />
<br />
<center><div class=" contenedor"><center><h2>Eliminar a un usuario</h2></center></div></center>


<center>
    <div class="TablaFormato">
        <h4>Datos del usuario</h4>


        <hr />
       <h3>¿Está seguro de eliminar el usuario</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-primary" /> |
                <a class="btn btn-success" @Html.ActionLink("Regresar a usuarios", "Index")
            </div>
        }
    </div>
</center>

Rio1.UI/Views/AspNetUsers/Index.cshtml
@model IEnumerable<Rio1.Model.AspNetUsers>

@{
    ViewBag.Title = "Datos de usuarios";
}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/Content/Estilos.css">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale-1.0, maximun-scale=3.0, minimun-scale=1.0">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script class="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
</head>
<br />
<br />
<div class="contenedor">
    <center><h2>Lista de usuarios</h2></center>
</div>
<br />
<br />
<p><a class="btn btn-info" @Html.ActionLink("Registrar un usuario", "Register", "Account")</a></p>

<br />
<center>
    <div class="TablaFormato">
        <center>
            <table id="table_id" class="display">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>


                        <th></th>
                    </tr>
                <thead>

                    @foreach (var item in Model)
                    {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>

                            <td>

                                <a class="btn btn-primary" @Html.ActionLink("Detalles", "Detallar", new { id = item.Id })
                                <a class="btn btn-danger" @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })

                            </td>
                        </tr>
                    </tbody>

                }

                </table>
            </center>
        </div>
    </center>
<br />
<br />
<p><a class="btn btn-success" @Html.ActionLink("Regresar a Inicio", "Index", "Home")</a></p>


    @section scripts{
        <script>
            $(document).ready(function () {
                $('#table_id').DataTable();
            })


        </script>
    }

Rio1.UI/Views/AspNetUsers/VistaGeneral.cshtml
@model IEnumerable<Rio1.Model.AspNetUsers>

@{
    ViewBag.Title = "VistaGeneral";
}


<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/Content/Estilos.css">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale-1.0, maximun-scale=3.0, minimun-scale=1.0">

</head>
<br />
<br />
<div class="contenedor">
    <center>
        <h2>
            Página administrativa de Usuarios

        </h2>
    </center>
    

</div>


<br />
<br />
<center>
    
        <div class="row">

            <div class="col-md-4">
                <div class=" Minicontenedor">
                    <center> <h2>Usuarios</h2></center>
                    <a href='@Url.Action("Index", "AspNetUsers")'> <center><img src="~/Content/imagenes/usuario.png" class="Alojamiento" text-align: center></center></a>
                </div>
            </div>


            <div class="col-md-4">
                <div class="Minicontenedor">
                    <center><h2>Roles </h2></center>
                    <a href='@Url.Action("Index", "AspNetRoles")'> <center><img src="~/Content/imagenes/analitica.png" class="Alojamiento" text-align: center></center></a>

                </div>
            </div>
        </div>
   
</center>